apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor-monitor-deployment
  labels:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: executor-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lp-etl
      app.kubernetes.io/component: executor-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lp-etl
        app.kubernetes.io/component: executor-monitor
    spec:
      volumes:
        - name: executor-volume
          persistentVolumeClaim:
            claimName: volume-claim
      containers:
        - name: executor-volume
          image: linkedpipes/etl-executor-monitor:develop
          imagePullPolicy: Always
          env:
            - name: LP_ETL_DOMAIN
              value: "http://localhost:8080"
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: "/data/lp-etl/"
              name: executor-volume
