apiVersion: v1
kind: Service
metadata:
  name: executor
  labels:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: executor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: executor
  ports:
  - protocol: TCP
    # Target port in pods.
    targetPort: 8085
    # Port for inside the cluster.
    port: 8085

