apiVersion: v1
kind: Service
metadata:
  name: executor-monitor
  labels:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: executor-monitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: executor-monitor
  ports:
  - protocol: TCP
    # Target port in pods.
    targetPort: 8081
    # Port for inside the cluster.
    port: 8081

