apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: frontend
  ports:
  - protocol: TCP
    # Target port in pods.
    targetPort: 8080
    # Port for inside the cluster.
    port: 8080
    # Outside port (there is a limit on range).
    nodePort: 31000
