apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lp-etl
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lp-etl
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: lp-etl-frontend
          image: linkedpipes/etl-frontend:develop
          imagePullPolicy: Always
          env:
            - name: LP_ETL_DOMAIN
              value: "http://localhost:8080"
          ports:
            - containerPort: 8080
