apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  labels:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: storage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lp-etl
      app.kubernetes.io/component: storage
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lp-etl
        app.kubernetes.io/component: storage
    spec:
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: volume-claim
      containers:
        - name: storage-volume
          image: linkedpipes/etl-storage:develop
          imagePullPolicy: Always
          env:
            - name: LP_ETL_DOMAIN
              value: "http://localhost:8080"
          ports:
            - containerPort: 8083
          volumeMounts:
            - mountPath: "/data/lp-etl/"
              name: storage-volume
