apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lp-etl
    app.kubernetes.io/component: storage
  ports:
  - protocol: TCP
    # Target port in pods.
    targetPort: 8083
    # Port for inside the cluster.
    port: 8083

