apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
  labels:
    app.kubernetes.io/name: lp-etl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: lp-etl
